vars:
  mysql_password: RoboShop@1

- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: java
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: check cities schema exists or not
    ansible.builtin.command:  mysql -h mysql.mvaws.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print output
    ansible.builtin.debug:
      msg: "schema output: {{schema}}"

  - name: load cities data
    ansible.builtin.shell: "mysql -h mysql.mvaws.online -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
    when: schema.stdout != "1"

- name: systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd

