- name: install golang
  ansible.builtin.package:
    name: golang
    state: present

- name: installing
  ansible.builtin.command: "{{item}}"
  loop:
  - go mod init dispatch
  - go get 
  - go build
  args:
    chdir: /app